export const PI_EXTENSION_COMMAND = "reins hook pi";

/** Source of the pi extension written to ~/.pi/agent/extensions/reins.ts.
 *  pi auto-loads that directory and runs TypeScript via jiti (no build step);
 *  the extension forwards every tool_call to `reins hook pi` and uses the
 *  tool_call block contract ({ block: true, reason }) on a non-zero exit. */
export function piExtensionSource(): string {
  return `// reins adapter — generated by \`reins init pi\`
// Forwards every tool_call to the reins policy and blocks via the
// tool_call block contract when the policy denies it. Delete this file to
// uninstall.
import { spawnSync } from "node:child_process";
import type { ExtensionAPI } from "@earendil-works/pi-coding-agent";

const COMMAND = ${JSON.stringify(PI_EXTENSION_COMMAND)};

export default function (pi: ExtensionAPI) {
  pi.on("tool_call", async (event) => {
    const payload = JSON.stringify({
      tool: event.toolName,
      args: (event.input as Record<string, unknown>) ?? {},
    });
    const r = spawnSync("reins", COMMAND.split(" ").slice(1), {
      input: payload,
      encoding: "utf8",
    });
    if (r.error || r.status !== 0) {
      const detail = ((r.stderr ?? "") + (r.error ? " (" + r.error.message + ")" : "")).trim();
      return { block: true, reason: detail || "[reins] blocked (fail-closed)" };
    }
  });
}
`;
}
