export const OPENCODE_PLUGIN_COMMAND = "reins hook opencode";

/** Source of the opencode plugin written to ~/.config/opencode/plugins/reins.js.
 *  opencode auto-loads that directory; the plugin forwards every tool call to
 *  `reins hook opencode` and blocks by throwing when it exits non-zero. */
export function opencodePluginSource(): string {
  return `// reins adapter — generated by \`reins init opencode\`
// Forwards every tool call to the reins policy and blocks by throwing
// when the policy denies it. Delete this file to uninstall.
import { spawnSync } from "node:child_process";

const COMMAND = ${JSON.stringify(OPENCODE_PLUGIN_COMMAND)};

export const Reins = async () => ({
  "tool.execute.before": async (input, output) => {
    const payload = JSON.stringify({
      tool: input.tool,
      args: output.args ?? {},
      session_id: input.sessionID ?? input.session_id,
    });
    const r = spawnSync("reins", COMMAND.split(" ").slice(1), {
      input: payload,
      encoding: "utf8",
    });
    if (r.error || r.status !== 0) {
      const detail = ((r.stderr ?? "") + (r.error ? " (" + r.error.message + ")" : "")).trim();
      throw new Error(detail || "[reins] blocked (fail-closed)");
    }
  },
});
`;
}
